project:
  type: website
  output-dir: ../docs

website:
  title: "POCUS-CARE"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Training Sessions
        menu:
          - href: training.qmd
            text: Training overview

          - href: provider-course.qmd
            text: Provider Course

          - href: instructor-course.qmd
            text: Instructor Course

      - href: /textbook/index.html
        text: Textbook

      - href: about.qmd
        text: About
        
      - href: resources.qmd
        text: Resources

      - href: contact.qmd
        text: Contact
          
  page-footer:
      left: "© 2026 POCUS-CARE"
      right: "Open educational resources for Point-of-Care Ultrasound"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body:
      - includes/cloudflare.html



