project:
  type: website
  output-dir: ../docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: training.qmd
        text: Training

      - href: /textbook/index.html
        text: Textbook

      - href: about.qmd
        text: About

      - href: contact.qmd
        text: Contact
          
  page-footer:
      left: "© 2026 POCUS-CARE"
      right: "Open educational resources for Point-of-Care Ultrasound"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



